import userSchema from "./user.schema";
import businessSchema from "./business.schema.ts";
import staySchema from "./stay.schema.ts";
import businessPaymentSchema from "./business_payment.schema.ts";
import businessTypeSchema from "./business_type.schema.ts";
import businessUploadSchema from "./business_upload.schema.ts";
import cancellationPolicySchema from "./cancellation_policy.schema.ts";
import countrySchema from "./country.schema.ts";
import galleryMediaSchema from "./gallery_media.schema.ts";
import reviewSchema from "./review.schema";
import squawkSchema from "./squawk.schema.ts";
import squawkCategorySchema from "./squawk_category.schema.ts";
import squawkCommentSchema from "./squawk_comment.schema.ts";
import squawkTagSchema from "./squawk_tag.schema.ts";
import stayCalendarSchema from "./stay_calendar.schema.ts";
import stayAirportSchema from "./stay_airport.schema.ts";
import bookingExpenseSchema from "./booking_expense.schema.ts";
import bookingSchema from "./booking.schema.ts";
import postCheckoutSchema from "./post_checkout.schema.ts";
import bookingTransactionSchema from "./booking_transaction.schema.ts";
import stayExtraServiceSchema from "./stay_extra_service.schema.ts";
import favouriteSchema from "./fav.schema.ts";
import stayFeatureSchema from "./stay_feature.schema.ts";
import stayImageSchema from "./stay_image.schema.ts";
import stayPlaceTypeSchema from "./stay_place_type.schema.ts";
import stayServiceTypeSchema from "./stay_service.schema.ts";
import staySpaceTypeSchema from "./stay_space_type.schema.ts";
import staySurfaceTypeSchema from "./stay_surface_type.schema.ts";
import testimonialSchema from "./testimonial.schema.ts";
import airportSchema from "./airport.schema.ts";
import chatSchema from "./chat.schema.ts";
import messageSchema from "./message.schema.ts";

export { chatSchema, messageSchema, testimonialSchema, staySurfaceTypeSchema, staySpaceTypeSchema, stayServiceTypeSchema, stayPlaceTypeSchema, stayImageSchema, stayFeatureSchema, favouriteSchema, stayExtraServiceSchema, bookingTransactionSchema, postCheckoutSchema, bookingSchema, bookingExpenseSchema, stayAirportSchema, stayCalendarSchema, squawkTagSchema, squawkCommentSchema, squawkCategorySchema, squawkSchema, reviewSchema, galleryMediaSchema, cancellationPolicySchema, userSchema, businessSchema, staySchema, businessPaymentSchema, businessTypeSchema, businessUploadSchema, countrySchema, airportSchema };

